<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\xampp\htdocs\Matodo\app\Presentation\Front\UI/@layout.latte */
final class Template_840b16fe9a extends Latte\Runtime\Template
{
	public const Blocks = [
		'snippet' => ['flash' => 'blockFlash', 'content' => 'blockContent'],
		0 => ['content' => 'blockContent1'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Antonín Zelený">
    <meta name="description"';
		echo LR\HtmlHelpers::formatAttribute(' content', $pageDescription) /* pos 12:40 */;
		echo '>
    <meta name="robots" content="index,follow">
    <meta property="og:title"';
		echo LR\HtmlHelpers::formatAttribute(' content', $pageTitle) /* pos 14:41 */;
		echo '>
    <meta property="og:description"';
		echo LR\HtmlHelpers::formatAttribute(' content', $pageDescription) /* pos 15:47 */;
		echo '>
    <meta property="og:image"';
		echo LR\HtmlHelpers::formatAttribute(' content', $ogImage) /* pos 16:41 */;
		echo '>
    <meta property="og:type" content="website">
';
		if ($canonicalUrl) /* pos 18:5 */ {
			echo '        <link rel="canonical"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)($canonicalUrl)) /* pos 19:38 */;
			echo '>
';
		}
		echo '    <link rel="icon" type="image/x-icon" href="';
		echo LR\HtmlHelpers::escapeAttr($basePath) /* pos 21:48 */;
		echo '/favicon.ico">
    <link rel="stylesheet" href="';
		echo LR\HtmlHelpers::escapeAttr($basePath) /* pos 22:34 */;
		echo '/css/Front/';
		echo LR\HtmlHelpers::escapeAttr($css) /* pos 22:56 */;
		echo '-scss.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "Organization",
          "name": "Matodo.cz",
          "url": ';
		if ($canonicalUrl) /* pos 29:18 */ {
			echo '"';
			echo LR\Helpers::escapeJs(($this->filters->escapeJs)($canonicalUrl)) /* pos 29:37 */;
			echo '"';
		} else /* pos 29:62 */ {
			echo '"';
		}
		echo ',
  "email": "info@matodo.cz",
  "telephone": "+18295430711"
}
    </script>
    <script src="https://unpkg.com/naja@2/dist/Naja.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/cs.js"></script>
    <script src="';
		echo LR\HtmlHelpers::escapeAttr($basePath) /* pos 37:18 */;
		echo '/js/Front/';
		if (isset($js)) /* pos 37:39 */ {
			echo LR\HtmlHelpers::escapeAttr($js) /* pos 37:54 */;
			echo '-js';
		} else /* pos 37:62 */ {
			echo 'master';
		}
		echo '.js" defer></script>
    <title>Matodo.cz - ';
		echo LR\HtmlHelpers::escapeText($pageTitle) /* pos 38:24 */;
		echo '</title>
</head>
<body>
';
		echo '<div id="', htmlspecialchars($this->global->snippetDriver->getHtmlId('flash')), '">';
		$this->renderBlock('flash', [], null, 'snippet') /* pos 41:1 */;
		echo '</div>

';
		echo '<div id="', htmlspecialchars($this->global->snippetDriver->getHtmlId('content')), '">';
		$this->renderBlock('content', [], null, 'snippet') /* pos 52:1 */;
		echo '</div>
';
		$ʟ_tmp = $this->global->uiControl->getComponent('footer');
		if ($ʟ_tmp instanceof Nette\Application\UI\Renderable) $ʟ_tmp->redrawControl(null, false);
		$ʟ_tmp->render() /* pos 56:1 */;

		echo '</body>
</html>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['flash' => '43'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$pageTitle = $pageTitle ?? 'Matodo.cz - Výlety Dominikánská republika' /* pos 1:1 */;
		$pageDescription = $pageDescription ?? 'Poznejte Dominikánskou republiku s profesionálními průvodci. Bezpečné výlety, nezapomenutelné zážitky a pohodlné rezervace online.' /* pos 2:1 */;
		$ogImage = $ogImage ?? $basePath . '/img/og-default.jpg' /* pos 3:1 */;
		$canonicalUrl = $canonicalUrl ?? null /* pos 4:1 */;
		return get_defined_vars();
	}


	/** {snippet flash} on line 41 */
	public function blockFlash(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->global->snippetDriver->enter('flash', 'static') /* pos 41:1 */;
		try {
			echo '
    <div class="flash-container">
';
			foreach ($flashes as $flash) /* pos 43:9 */ {
				echo '            <div class="flash flash--';
				echo LR\HtmlHelpers::escapeAttr($flash->type) /* pos 44:38 */;
				echo '">
                <span>';
				echo LR\HtmlHelpers::escapeText($flash->message) /* pos 45:23 */;
				echo '</span>
                <button type="button" class="flash__close" data-close="flash">×</button>
            </div>
';

			}

			echo '    </div>
';

		} finally {
			$this->global->snippetDriver->leave();
		}
	}


	/** {snippet content} on line 52 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->global->snippetDriver->enter('content', 'static') /* pos 52:1 */;
		try {
			echo "\n";
			$this->renderBlock('content', get_defined_vars()) /* pos 53:5 */;
		} finally {
			$this->global->snippetDriver->leave();
		}
	}


	/** {block content} on line 53 */
	public function blockContent1(array $ʟ_args): void
	{
	}
}
