<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\xampp\htdocs\Matodo\app\Presentation\Admin\UI/@layout.latte */
final class Template_bd82c0a6cc extends Latte\Runtime\Template
{
	public const Blocks = [
		'snippet' => ['flash' => 'blockFlash', 'content' => 'blockContent'],
		0 => ['content' => 'blockContent1'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Antonín Zelený">
    <link rel="icon" type="image/x-icon" href="';
		echo LR\HtmlHelpers::escapeAttr($basePath) /* pos 7:48 */;
		echo '/favicon.ico">
    <link rel="stylesheet" href="';
		echo LR\HtmlHelpers::escapeAttr($basePath) /* pos 8:34 */;
		echo '/css/Admin/';
		echo LR\HtmlHelpers::escapeAttr($css) /* pos 8:56 */;
		echo '-scss.css">
    <script src="https://unpkg.com/naja@2/dist/Naja.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/dayjs@1/dayjs.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/dayjs@1/locale/cs.js"></script>
    <script>
        dayjs.locale(\'cs\');
    </script>
    <script src="';
		echo LR\HtmlHelpers::escapeAttr($basePath) /* pos 16:18 */;
		echo '/js/Admin/';
		if (isset($js)) /* pos 16:39 */ {
			echo LR\HtmlHelpers::escapeAttr($js) /* pos 16:54 */;
			echo '-js';
		} else /* pos 16:62 */ {
			echo 'master';
		}
		echo '.js" defer></script>
    <script src="';
		echo LR\HtmlHelpers::escapeAttr($basePath) /* pos 17:18 */;
		echo '/js/Admin/flash-js.js" defer></script>
    <title>Web</title>
</head>
<body>
';
		echo '<div id="', htmlspecialchars($this->global->snippetDriver->getHtmlId('flash')), '">';
		$this->renderBlock('flash', [], null, 'snippet') /* pos 21:1 */;
		echo '</div>

';
		echo '<div id="', htmlspecialchars($this->global->snippetDriver->getHtmlId('content')), '">';
		$this->renderBlock('content', [], null, 'snippet') /* pos 32:1 */;
		echo '</div>
</body>
</html>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['flash' => '23'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}


	/** {snippet flash} on line 21 */
	public function blockFlash(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->global->snippetDriver->enter('flash', 'static') /* pos 21:1 */;
		try {
			echo '
    <div class="flash-container">
';
			foreach ($flashes as $flash) /* pos 23:9 */ {
				echo '            <div class="flash flash--';
				echo LR\HtmlHelpers::escapeAttr($flash->type) /* pos 24:38 */;
				echo '">
                <span>';
				echo LR\HtmlHelpers::escapeText($flash->message) /* pos 25:23 */;
				echo '</span>
                <button type="button" class="flash__close" data-close="flash">×</button>
            </div>
';

			}

			echo '    </div>
';

		} finally {
			$this->global->snippetDriver->leave();
		}
	}


	/** {snippet content} on line 32 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->global->snippetDriver->enter('content', 'static') /* pos 32:1 */;
		try {
			echo '
    <div class="admin-layout">

        <aside class="admin-sidebar">
            <div class="admin-sidebar__header">
                <div class="admin-sidebar__title">Admin Panel</div>
            </div>

            <hr class="admin-sidebar__divider">

            <nav class="admin-sidebar__nav">
                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Admin:Home:default')) /* pos 43:20 */;
			echo '"
                        class="admin-sidebar__nav-item ';
			if (($this->global->fn->isLinkCurrent)($this, ':Admin:Home:*')) /* pos 44:56 */ {
				echo 'is-active';
			}
			echo '">
                    <span class="admin-sidebar__nav-icon">▦</span>
                    <span>Dashboard</span>
                </a>

                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Admin:Calendar:default')) /* pos 49:20 */;
			echo '"
                        class="admin-sidebar__nav-item ';
			if (($this->global->fn->isLinkCurrent)($this, ':Admin:Calendar:*')) /* pos 50:56 */ {
				echo 'is-active';
			}
			echo '">
                    <span class="admin-sidebar__nav-icon">🗓</span>
                    <span>Kalendář</span>
                </a>

                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Admin:Inquiry:default')) /* pos 55:20 */;
			echo '"
                        class="admin-sidebar__nav-item ';
			if (($this->global->fn->isLinkCurrent)($this, ':Admin:Inquiry:*')) /* pos 56:56 */ {
				echo 'is-active';
			}
			echo '">
                    <span class="admin-sidebar__nav-icon">💬</span>
                    <span>Dotazy</span>
                </a>

                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Admin:Trips:default')) /* pos 61:20 */;
			echo '"
                        class="admin-sidebar__nav-item ';
			if (($this->global->fn->isLinkCurrent)($this, ':Admin:Trips:*')) /* pos 62:56 */ {
				echo 'is-active';
			}
			echo '">
                    <span class="admin-sidebar__nav-icon">🗺</span>
                    <span>Výlety</span>
                </a>

                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Admin:Transfer:default')) /* pos 67:20 */;
			echo '"
                        class="admin-sidebar__nav-item ';
			if (($this->global->fn->isLinkCurrent)($this, ':Admin:Transfer:*')) /* pos 68:56 */ {
				echo 'is-active';
			}
			echo '">
                    <span class="admin-sidebar__nav-icon">🚗</span>
                    <span>Transfer</span>
                </a>

                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Admin:Reservations:default')) /* pos 73:20 */;
			echo '"
                        class="admin-sidebar__nav-item ';
			if (($this->global->fn->isLinkCurrent)($this, ':Admin:Reservations:*')) /* pos 74:56 */ {
				echo 'is-active';
			}
			echo '">
                    <span class="admin-sidebar__nav-icon">📅</span>
                    <span>Rezervace</span>
                </a>
            </nav>

            <hr class="admin-sidebar__divider admin-sidebar__divider--bottom">

            <div class="admin-sidebar__bottom">
                <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)($baseUrl)) /* pos 83:27 */;
			echo ' class="admin-sidebar__back">
                    <span class="admin-sidebar__back-icon">🏠</span>
                    <span>Zpět na web</span>
                </a>
            </div>
        </aside>

        <main class="admin-content">
';
			$this->renderBlock('content', get_defined_vars()) /* pos 91:13 */;
			echo '        </main>
    </div>
';

		} finally {
			$this->global->snippetDriver->leave();
		}
	}


	/** {block content} on line 91 */
	public function blockContent1(array $ʟ_args): void
	{
	}
}
