<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\xampp\htdocs\Matodo\app\Presentation\Admin\UI\Calendar/default.latte */
final class Template_13a69af36c extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$css = 'calendar' /* pos 1:1 */;
		$js = 'calendar' /* pos 2:1 */;
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '
    <div id="adminCalendar"
         class="admin-calendar"';
		echo LR\HtmlHelpers::formatDataAttribute('
         data-month', ($this->filters->date)($currentMonth, 'Y-m-01')) /* pos 7:23 */;
		echo LR\HtmlHelpers::formatDataAttribute('
         data-events', json_encode($eventsByDate)) /* pos 8:25 */;
		echo '>

    <div class="admin-calendar__left">
                <div class="admin-calendar__header">
                    <button type="button" class="admin-calendar__nav" data-calendar-prev>
                        ←
                    </button>

                    <div class="admin-calendar__month" data-calendar-label>
                        <!-- sem doplní JS (např. prosinec 2025) -->
                    </div>

                    <button type="button" class="admin-calendar__nav" data-calendar-next>
                        →
                    </button>
                </div>

                <div class="admin-calendar__weekdays">
                    <span>Po</span>
                    <span>Út</span>
                    <span>St</span>
                    <span>Čt</span>
                    <span>Pá</span>
                    <span>So</span>
                    <span>Ne</span>
                </div>

                <div class="admin-calendar__grid" data-calendar-grid>
                    <!-- generuje JS -->
                </div>
    </div>

        <div class="admin-calendar__right">
            <h2 class="admin-calendar-detail__date" data-calendar-detail-date>
                <!-- sem doplní JS (např. 8. prosince 2025) -->
            </h2>

            <div class="admin-calendar-detail__content" data-calendar-detail-list>
                <p class="admin-calendar-detail__empty">
                    Žádné výlety na tento den.
                </p>
            </div>
        </div>
    </div>

';
		if ($showDetailModal && $detailReservation) /* pos 55:5 */ {
			echo '        <div class="reservations-modal-backdrop">
            <div class="reservations-modal reservations-modal--detail">
                <div class="reservations-modal__header">
                    <h2>Detail rezervace</h2>
                    <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('this')) /* pos 60:24 */;
			echo '" class="reservations-modal__close">×</a>
                </div>

                <div class="reservation-detail">

                    <section class="reservation-detail__section">
                        <h3>Zákazník</h3>

                        <div class="reservation-detail__row">
                            <div class="reservation-detail__field">
                                <div class="reservation-detail__label">Jméno:</div>
                                <div class="reservation-detail__value">
                                    ';
			echo LR\HtmlHelpers::escapeText($detailReservation->customer_name) /* pos 72:37 */;
			echo '
                                </div>
                            </div>

                            <div class="reservation-detail__field">
                                <div class="reservation-detail__label">Email:</div>
                                <div class="reservation-detail__value">
                                    ';
			echo LR\HtmlHelpers::escapeText($detailReservation->customer_email) /* pos 79:37 */;
			echo '
                                </div>
                            </div>
                        </div>

                        <div class="reservation-detail__row">
                            <div class="reservation-detail__field">
                                <div class="reservation-detail__label">Telefon:</div>
                                <div class="reservation-detail__value">
                                    ';
			echo LR\HtmlHelpers::escapeText($detailReservation->customer_phone) /* pos 88:37 */;
			echo '
                                </div>
                            </div>

                            <div class="reservation-detail__field">
                                <div class="reservation-detail__label">Počet osob:</div>
                                <div class="reservation-detail__value">
                                    ';
			echo LR\HtmlHelpers::escapeText($detailReservation->guests) /* pos 95:37 */;
			echo '
                                </div>
                            </div>
                        </div>

                        <div class="reservation-detail__row">
                            <div class="reservation-detail__field">
                                <div class="reservation-detail__label">Místo vyzvednutí:</div>
                                <div class="reservation-detail__value">
                                    ';
			echo LR\HtmlHelpers::escapeText($detailReservation->pickup_point) /* pos 104:37 */;
			echo '
                                </div>
                            </div>

                            <div class="reservation-detail__field">
                                <div class="reservation-detail__label">Poznámka:</div>
                                <div class="reservation-detail__value">
                                    ';
			echo LR\HtmlHelpers::escapeText($detailReservation->notes) /* pos 111:37 */;
			echo '
                                </div>
                            </div>
                        </div>
                    </section>

                    <section class="reservation-detail__section">
                        <h3>Výlet</h3>

                        <div class="reservation-detail__row">
                            <div class="reservation-detail__field reservation-detail__field--full">
                                <div class="reservation-detail__label">Název:</div>
                                <div class="reservation-detail__value">
                                    <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Front:Excursion:default', [$detailReservation->trip->id])) /* pos 124:40 */;
			echo '"
                                            target="_blank"
                                            class="reservation-detail__trip-link">
                                        ';
			echo LR\HtmlHelpers::escapeText($detailReservation->trip->title) /* pos 127:41 */;
			echo '
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="reservation-detail__row">
                            <div class="reservation-detail__field">
                                <div class="reservation-detail__label">Lokace:</div>
                                <div class="reservation-detail__value">
                                    ';
			echo LR\HtmlHelpers::escapeText($detailReservation->trip->location) /* pos 137:37 */;
			echo '
                                </div>
                            </div>

                            <div class="reservation-detail__field">
                                <div class="reservation-detail__label">Délka:</div>
                                <div class="reservation-detail__value">
                                    ';
			echo LR\HtmlHelpers::escapeText($detailReservation->trip->duration) /* pos 144:37 */;
			echo '
                                </div>
                            </div>
                        </div>

                        <div class="reservation-detail__row">
                            <div class="reservation-detail__field">
                                <div class="reservation-detail__label">Cena:</div>
                                <div class="reservation-detail__value">
                                    ';
			echo LR\HtmlHelpers::escapeText(($this->filters->number)($detailReservation->trip->price, 0, ',', ' ')) /* pos 153:37 */;
			echo ' USD
                                </div>
                            </div>
                        </div>
                    </section>

                    <section class="reservation-detail__section">
                        <h3>Rezervace</h3>

                        <div class="reservation-detail__row">
                            <div class="reservation-detail__field">
                                <div class="reservation-detail__label">Datum:</div>
                                <div class="reservation-detail__value">
                                    ';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($detailReservation->date, 'j. n. Y')) /* pos 166:37 */;
			echo '
                                </div>
                            </div>

                            <div class="reservation-detail__field">
                                <div class="reservation-detail__label">Status:</div>
                                <div class="reservation-detail__value">
                                <span class="reservation-status reservation-status--';
			echo LR\HtmlHelpers::escapeAttr($detailReservation->status) /* pos 173:85 */;
			echo '">
';
			if ($detailReservation->status === 'confirm') /* pos 174:37 */ {
				echo '                                        Potvrzeno
';
			} elseif ($detailReservation->status === 'canceled') /* pos 176:37 */ {
				echo '                                        Zrušeno
';
			} else /* pos 178:37 */ {
				echo '                                        Čeká
';
			}

			echo '                                </span>
                                </div>
                            </div>
                        </div>

                        <div class="reservation-detail__row">
                            <div class="reservation-detail__field reservation-detail__field--full">
                                <div class="reservation-detail__label">Vytvořeno:</div>
                                <div class="reservation-detail__value">
                                    ';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($detailReservation->created_at, 'j. n. Y, H:i')) /* pos 190:37 */;
			echo '
                                </div>
                            </div>
                        </div>
                    </section>

                </div>
            </div>
        </div>
';
		}
		if ($showTransferDetailModal && $detailTransfer) /* pos 200:5 */ {
			echo '        <div class="tdm-backdrop" data-modal="transfer-detail">
            <div class="tdm-modal" role="dialog" aria-modal="true" aria-label="Detail rezervace transferu">

                <div class="tdm-header">
                    <h2 class="tdm-title">Detail rezervace transferu</h2>
                    <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('this')) /* pos 206:24 */;
			echo '" class="tdm-close" aria-label="Zavřít" data-modal-close>×</a>
                </div>

                <div class="tdm-body">
                    <div class="tdm-topgrid">
                        <div class="tdm-block">
                            <div class="tdm-label">Zákazník</div>
                            <div class="tdm-strong">';
			echo LR\HtmlHelpers::escapeText($detailTransfer->customer_name) /* pos 213:53 */;
			echo '</div>
                        </div>

                        <div class="tdm-block tdm-block--right">
                            <div class="tdm-label">Stav</div>
                            <span class="tdm-badge tdm-badge--';
			echo LR\HtmlHelpers::escapeAttr($detailTransfer->status) /* pos 218:63 */;
			echo '">
              ';
			if ($detailTransfer->status === 'confirm') /* pos 219:15 */ {
				echo 'Potvrzeno
              ';
			} elseif ($detailTransfer->status === 'canceled') /* pos 220:15 */ {
				echo 'Zrušeno
              ';
			} else /* pos 221:15 */ {
				echo 'Čeká';
			}

			echo '
            </span>
                        </div>

                        <div class="tdm-contact">
                            <span class="tdm-ico" aria-hidden="true">✉️</span>
                            <a href="mailto:';
			echo LR\HtmlHelpers::escapeAttr($detailTransfer->customer_email) /* pos 227:45 */;
			echo '" class="tdm-link">';
			echo LR\HtmlHelpers::escapeText($detailTransfer->customer_email) /* pos 227:97 */;
			echo '</a>
                        </div>

                        <div class="tdm-contact">
                            <span class="tdm-ico" aria-hidden="true">📞</span>
                            <a href="tel:';
			echo LR\HtmlHelpers::escapeAttr($detailTransfer->customer_phone) /* pos 232:42 */;
			echo '" class="tdm-link">';
			echo LR\HtmlHelpers::escapeText($detailTransfer->customer_phone) /* pos 232:94 */;
			echo '</a>
                        </div>
                    </div>

                    <hr class="tdm-sep">

                    <div class="tdm-meta">
                        <div class="tdm-meta-item"><span class="tdm-ico">📅</span>
                            <span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($detailTransfer->pickup_date, 'j. n. Y')) /* pos 240:35 */;
			echo '</span>
                        </div>
                        <div class="tdm-meta-item"><span class="tdm-ico">🕒</span>
                            <span>';
			echo LR\HtmlHelpers::escapeText($detailTransfer->pickup_time->format('%H:%I')) /* pos 243:35 */;
			echo '</span>
                        </div>
                        <div class="tdm-meta-item"><span class="tdm-ico">👥</span>
                            <span>';
			echo LR\HtmlHelpers::escapeText($detailTransfer->passagers) /* pos 246:35 */;
			echo ' pasažérů</span>
                        </div>
                    </div>

                    <hr class="tdm-sep">

                    <div class="tdm-section">
                        <div class="tdm-label">Trasa</div>
                        <div class="tdm-route">
                            <div class="tdm-route-row">
                                <div class="tdm-route-k">Z:</div>
                                <div class="tdm-route-v">';
			echo LR\HtmlHelpers::escapeText($detailTransfer->pickup_location) /* pos 257:58 */;
			echo '</div>
                            </div>
                            <div class="tdm-route-row">
                                <div class="tdm-route-k">Do:</div>
                                <div class="tdm-route-v">';
			echo LR\HtmlHelpers::escapeText($detailTransfer->dropoff_location) /* pos 261:58 */;
			echo '</div>
                            </div>
                        </div>
                    </div>

                    <div class="tdm-footer">
                        Vytvořeno: ';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($detailTransfer->created_at, 'j. n. Y H:i')) /* pos 267:37 */;
			echo '
                    </div>
                </div>
            </div>
        </div>
';
		}
		echo '

';
	}
}
