<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\xampp\htdocs\Matodo\app\Presentation\Front\UI\Excursion/default.latte */
final class Template_0e80d0c227 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 7:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['item' => '34', 'key' => '148', 'label' => '148'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$css = 'excursion' /* pos 1:1 */;
		$js = 'excursion' /* pos 2:1 */;
		$pageTitle = $trip->title . ' Výlety Dominikánská republika' /* pos 3:1 */;
		$pageDescription = $trip->description ?: 'Výlety Dominikánská republika: ' . $trip->title /* pos 4:1 */;
		$ogImage = $basePath . '/img/' . $trip->img_folder . '/' . $trip->img_name /* pos 5:1 */;
		return get_defined_vars();
	}


	/** {block content} on line 7 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '
    <div class="trip-hero" style="background-image: url(\'';
		echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeCss($basePath)) /* pos 9:58 */;
		echo '/img/';
		echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeCss($trip->img_folder)) /* pos 9:74 */;
		echo '/';
		echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeCss($trip->img_name)) /* pos 9:94 */;
		echo '\')">
        <div class="trip-hero__overlay">
            <div class="trip-hero__inner">
                <a href="';
		echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('Home:default')) /* pos 12:20 */;
		echo '" class="trip-hero__back">← Zpět na výlety</a>
                <h1 class="trip-hero__title">';
		echo LR\HtmlHelpers::escapeText($trip->title) /* pos 13:46 */;
		echo '</h1>
                <p class="trip-hero__subtitle">';
		echo LR\HtmlHelpers::escapeText($trip->description) /* pos 14:48 */;
		echo '</p>
            </div>
        </div>
    </div>

    <section class="trip-main">
        <div class="trip-main__inner">

            <div class="trip-main__left">
                <section class="trip-section">
                    <h2>O výletu</h2>
                    <p class="trip-section__text">
                        ';
		echo LR\HtmlHelpers::escapeText(($this->filters->breaklines)($trip->full_description)) /* pos 26:25 */;
		echo '
                    </p>
                </section>

                <section class="trip-section trip-section--columns">
                    <div class="trip-section__col">
                        <h2>Co je zahrnuto</h2>
                        <ul class="trip-list trip-list--included">
';
		foreach ($included as $item) /* pos 34:29 */ {
			if (trim($item) !== '') /* pos 35:33 */ {
				echo '                                    <li>';
				echo LR\HtmlHelpers::escapeText($item) /* pos 36:41 */;
				echo '</li>
';
			}

		}

		echo '                        </ul>
                    </div>

                    <div class="trip-section__col">

                    </div>
                </section>
            </div>

            <aside class="trip-main__right">
                <div class="trip-price-card">
                    <div class="trip-price-card__price">
                    <span class="trip-price-card__amount">
                        od ';
		echo LR\HtmlHelpers::escapeText(($this->filters->number)($trip->price, 0, ',', ' ')) /* pos 52:28 */;
		echo ' USD
                    </span>
                        <span class="trip-price-card__per">na osobu</span>
                    </div>

                    <div class="trip-price-card__meta">
                        <div class="trip-meta-item">
                            <span class="trip-meta-item__icon">⏱</span>
                            <span>';
		echo LR\HtmlHelpers::escapeText($trip->duration) /* pos 60:35 */;
		echo '</span>
                        </div>
                        <div class="trip-meta-item">
                            <span class="trip-meta-item__icon">👥</span>
                            <span>Až ';
		echo LR\HtmlHelpers::escapeText($trip->group_size) /* pos 64:39 */;
		echo ' lidí</span>
                        </div>
                        <div class="trip-meta-item">
                            <span class="trip-meta-item__icon">📍</span>
                            <span>';
		echo LR\HtmlHelpers::escapeText($trip->location) /* pos 68:35 */;
		echo '</span>
                        </div>
                    </div>

                    <a href="';
		echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('reservation!', [$trip->id])) /* pos 72:24 */;
		echo '" class="trip-price-card__button">
                        Rezervovat výlet
                    </a>

                    <div class="trip-price-card__note">
                        Bezplatné zrušení až 24 hodin před začátkem
                    </div>
                </div>

                <div class="trip-help-card">
                    <h3>Potřebujete pomoc? Není volný termín?</h3>
                    <p>Kontaktujte nás pro více informací nebo pro rezervaci.</p>
                    <a href="';
		echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('Home:default#kontakt')) /* pos 84:24 */;
		echo '" class="trip-help-card__button">
                        Kontaktovat nás
                    </a>
                </div>
            </aside>

        </div>
    </section>

';
		if ($showReservationModal) /* pos 93:5 */ {
			echo '        <div class="reservation-modal-backdrop">
            <div class="reservation-modal reservation-modal--wide">

                <div class="reservation-modal__header">
                    <h2>Rezervace: ';
			echo LR\HtmlHelpers::escapeText($trip->title) /* pos 98:36 */;
			echo '</h2>
                    <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('this')) /* pos 99:24 */;
			echo '" class="reservation-modal__close">×</a>
                </div>

                <div class="reservation-modal__body">
';
			if (empty($allowedDates)) /* pos 103:21 */ {
				echo '                        <p style="margin: 0; text-align: center; color: #6b7280; font-size: 15px; line-height: 1.6;">
                            Momentálně nejsou k dispozici žádné termíny pro tento výlet.<br>
                            Kontaktujte nás pro více informací, přes formulář nebo WhatsApp.
                        </p>
';
			} else /* pos 108:21 */ {
				echo '
                        <div class="reservation-modal__layout">

                            <div class="reservation-modal__formcol">
                                ';
				$form = $this->global->formsStack[] = $this->global->uiControl['reservationForm'] /* pos 113:33 */;
				Nette\Bridges\FormsLatte\Runtime::initializeForm($form);
				echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form, []) /* pos 113:33 */;
				echo '
                                    ';
				echo Nette\Bridges\FormsLatte\Runtime::item('trip_id', $this->global)->getControl() /* pos 114:37 */;
				echo '
                                    ';
				echo Nette\Bridges\FormsLatte\Runtime::item('token', $this->global)->getControl() /* pos 115:37 */;
				echo '

                                    <div class="reservation-form__group">
                                        <label for="frm-reservationForm-name">Jméno a příjmení *</label>
                                        ';
				echo Nette\Bridges\FormsLatte\Runtime::item('name', $this->global)->getControl() /* pos 119:41 */;
				echo '
                                    </div>

                                    <div class="reservation-form__group">
                                        <label for="frm-reservationForm-email">Email *</label>
                                        ';
				echo Nette\Bridges\FormsLatte\Runtime::item('email', $this->global)->getControl() /* pos 124:41 */;
				echo '
                                    </div>

                                    <div class="reservation-form__group">
                                        <label for="frm-reservationForm-phone">Telefon</label>
                                        ';
				echo Nette\Bridges\FormsLatte\Runtime::item('phone', $this->global)->getControl() /* pos 129:41 */;
				echo '
                                    </div>

                                    <div class="reservation-form__group">
                                        <label for="frm-reservationForm-date">Datum výletu *</label>
                                        <div class="reservation-form__date-wrapper">
                                            <span class="reservation-form__date-icon"></span>
                                            ';
				echo Nette\Bridges\FormsLatte\Runtime::item('date', $this->global)->getControl()->addAttributes(['data-allowed-dates' => $allowedDatesJson]) /* pos 136:45 */;
				echo '
                                        </div>
                                    </div>

                                    <div class="reservation-form__group">
                                        <label for="frm-reservationForm-persons">Počet osob *</label>
                                        ';
				echo Nette\Bridges\FormsLatte\Runtime::item('persons', $this->global)->getControl() /* pos 142:41 */;
				echo '
                                    </div>

                                    <div class="reservation-form__group">
                                        <label>Místo vyzvednutí *</label>
                                        <div class="pickup-options">
';
				foreach ($form['pickup']->items as $key => $label) /* pos 148:45 */ {
					echo '                                                <label class="pickup-option">
                                                    ';
					echo Nette\Bridges\FormsLatte\Runtime::item('pickup', $this->global)->getControlPart($key) /* pos 150:53 */;
					echo '
                                                    <span class="pickup-option__text">';
					echo LR\HtmlHelpers::escapeText($label) /* pos 151:87 */;
					echo '</span>
                                                </label>
';

				}

				echo '                                        </div>
                                    </div>

                                    <div class="reservation-form__group">
                                        <label for="frm-reservationForm-note">Poznámka a přesná lokace vyzvednutí</label>
                                        ';
				echo Nette\Bridges\FormsLatte\Runtime::item('note', $this->global)->getControl() /* pos 159:41 */;
				echo '
                                    </div>

                                    <button';
				echo ($ʟ_elem = Nette\Bridges\FormsLatte\Runtime::item('send', $this->global)->getControlPart())->addAttributes(['class' => null])->attributes() /* pos 162:45 */;
				echo ' class="reservation-modal__submit">
                                        Odeslat rezervaci
                                    </button>
                                ';
				echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack)) /* pos 165:33 */;

				echo '
                            </div>

                            <aside class="reservation-modal__summary">
                                <div class="res-summary__title">Souhrn ceny</div>

                                <div class="res-summary__line">
                                    <span>Cena za osobu</span>
                                    <strong><span data-price="pp">0</span> USD</strong>
                                </div>

                                <div class="res-summary__line">
                                    <span>Počet osob</span>
                                    <strong><span data-price="persons">1</span></strong>
                                </div>

                                <div class="res-summary__divider"></div>

                                <div class="res-summary__total">
                                    <span>Celkem</span>
                                    <strong><span data-price="total">0</span> USD</strong>
                                </div>

                                <div class="res-summary__note">
                                    Konečná cena může být upřesněna podle domluvy a dostupnosti.
                                </div>
                            </aside>

                        </div>

                        <script>
                            window.pickupPrices = ';
				echo LR\HtmlHelpers::convertJSToRawText($pickupPricesJson) /* pos 196:51 */;
				echo ';
                        </script>

';
			}
			echo '                </div>

            </div>
        </div>
';
		}
		echo "\n";
	}
}
