<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\xampp\htdocs\Matodo\app\Presentation\Admin\UI\Home/default.latte */
final class Template_a652bde99f extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['i' => '129, 163', 'trip' => '129, 163, 263'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$css = 'home' /* pos 1:1 */;
		$js = 'home' /* pos 2:1 */;
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="admin-dashboard">

    <header class="admin-dashboard__header">
        <h1>Dashboard</h1>
    </header>

    <section class="admin-dashboard__stats">
        <div class="admin-card">
            <div class="admin-card__header">
                <span class="admin-card__title">Dotazy</span>
                <span class="admin-card__icon">💬</span>
            </div>
            <div class="admin-card__value">';
		echo LR\HtmlHelpers::escapeText($inquiriesCount) /* pos 16:44 */;
		echo '</div>
            <div class="admin-card__subtext">
                ';
		echo LR\HtmlHelpers::escapeText($newInquiriesCount) /* pos 18:17 */;
		echo ' nových
            </div>
        </div>

        <div class="admin-card">
            <div class="admin-card__header">
                <span class="admin-card__title">Výlety</span>
                <span class="admin-card__icon admin-card__icon--green">🗺</span>
            </div>
            <div class="admin-card__value">';
		echo LR\HtmlHelpers::escapeText($tripsCount) /* pos 27:44 */;
		echo '</div>
            <div class="admin-card__subtext">
                v nabídce
            </div>
        </div>

        <div class="admin-card">
            <div class="admin-card__header">
                <span class="admin-card__title">Rezervace</span>
                <span class="admin-card__icon admin-card__icon--orange">📅</span>
            </div>
            <div class="admin-card__value">';
		echo LR\HtmlHelpers::escapeText($reservationsCount) /* pos 38:44 */;
		echo '</div>
            <div class="admin-card__subtext">
                ';
		echo LR\HtmlHelpers::escapeText($pendingReservationsCount) /* pos 40:17 */;
		echo ' čeká na potvrzení
            </div>
        </div>

        <div class="admin-card">
            <div class="admin-card__header">
                <span class="admin-card__title">Zobrazení výletů</span>
                <span class="admin-card__icon admin-card__icon--purple">👁</span>
            </div>
            <div class="admin-card__value">';
		echo LR\HtmlHelpers::escapeText($viewsCount) /* pos 49:44 */;
		echo '</div>
            <div class="admin-card__subtext">
                celkem
            </div>
        </div>

        <div class="admin-card">
            <div class="admin-card__header">
                <span class="admin-card__title">Opuštěné rezervace</span>
                <span class="admin-card__icon admin-card__icon--danger">⚠</span>
            </div>
            <div class="admin-card__value">';
		echo LR\HtmlHelpers::escapeText($abandonedPercent) /* pos 60:44 */;
		echo '%</div>
            <div class="admin-card__subtext">
                nedokončených
            </div>
        </div>
    </section>

    <section class="admin-dashboard__grid">
        <div class="admin-panel">
            <div class="admin-panel__header">
                <span class="admin-panel__title">
                    <span class="admin-panel__title-icon">📊</span>
                    Rezervace podle měsiců
                </span>
            </div>

            <div class="admin-panel__body admin-panel__body--chart">
                <canvas id="reservationsChart"';
		echo LR\HtmlHelpers::formatDataAttribute('
                        data-labels', json_encode(array_keys($reservationsByMonth))) /* pos 78:40 */;
		echo LR\HtmlHelpers::formatDataAttribute('
                        data-values', json_encode(array_values($reservationsByMonth))) /* pos 79:40 */;
		echo '>
                </canvas>
            </div>
        </div>

        <div class="admin-panel">
            <div class="admin-panel__header">
                <span class="admin-panel__title">
                    <span class="admin-panel__title-icon">📈</span>
                    Konverze: Zobrazení vs Rezervace
                </span>
            </div>

            <div class="admin-panel__body admin-panel__body--conversion">
                <div class="admin-conversion">
                    <div class="admin-conversion__item">
                        <div class="admin-conversion__icon admin-conversion__icon--blue">👁</div>
                        <div class="admin-conversion__value">';
		echo LR\HtmlHelpers::escapeText($conversionViews) /* pos 96:62 */;
		echo '</div>
                        <div class="admin-conversion__label">Zobrazení</div>
                    </div>

                    <div class="admin-conversion__item">
                        <div class="admin-conversion__icon admin-conversion__icon--green">🛒</div>
                        <div class="admin-conversion__value">';
		echo LR\HtmlHelpers::escapeText($conversionReservations) /* pos 102:62 */;
		echo '</div>
                        <div class="admin-conversion__label">Rezervace</div>
                    </div>
                </div>

                <div class="admin-conversion__divider"></div>

                <div class="admin-conversion__footer">
                    Konverzní poměr: <strong>';
		echo LR\HtmlHelpers::escapeText($conversionRate) /* pos 110:48 */;
		echo '%</strong>
                </div>
            </div>
        </div>
    </section>
    <section class="admin-dashboard__grid-secondary">

    <div class="admin-panel admin-panel--toplist admin-panel--toplist-green">
                <div class="admin-panel__header">
            <span class="admin-panel__title">
                <span class="admin-panel__title-icon">📈</span>
                Top 3 nejprodávanější výlety
            </span>
                </div>

                <div class="admin-panel__body">
                    <div class="admin-toplist">
';
		if ($topBestTrips) /* pos 128:25 */ {
			foreach ($topBestTrips as $i => $trip) /* pos 129:29 */ {
				echo '                                <div class="admin-toplist__item">
                                    <div class="admin-toplist__rank">
                                        #';
				echo LR\HtmlHelpers::escapeText($i + 1) /* pos 132:42 */;
				echo '
                                    </div>
                                    <div class="admin-toplist__content">
                                        <div class="admin-toplist__name">
                                            ';
				echo LR\HtmlHelpers::escapeText($trip->name) /* pos 136:45 */;
				echo '
                                        </div>
                                        <div class="admin-toplist__meta">
                                            ';
				echo LR\HtmlHelpers::escapeText($trip->reservations) /* pos 139:45 */;
				echo ' rezervací
                                        </div>
                                    </div>
                                </div>
';

			}

		} else /* pos 144:25 */ {
			echo '                            <p class="admin-toplist__empty">Zatím žádné rezervace.</p>
';
		}
		echo '                    </div>
                </div>
    </div>

    <div class="admin-panel admin-panel--toplist admin-panel--toplist-orange">
                <div class="admin-panel__header">
            <span class="admin-panel__title">
                <span class="admin-panel__title-icon">⚠</span>
                Top 3 nejméně prodávané výlety
            </span>
                </div>

                <div class="admin-panel__body">
                    <div class="admin-toplist">
';
		if ($topWorstTrips) /* pos 162:25 */ {
			foreach ($topWorstTrips as $i => $trip) /* pos 163:29 */ {
				echo '                                <div class="admin-toplist__item">
                                    <div class="admin-toplist__rank">
                                        #';
				echo LR\HtmlHelpers::escapeText($i + 1) /* pos 166:42 */;
				echo '
                                    </div>
                                    <div class="admin-toplist__content">
                                        <div class="admin-toplist__name">
                                            ';
				echo LR\HtmlHelpers::escapeText($trip->name) /* pos 170:45 */;
				echo '
                                        </div>
                                        <div class="admin-toplist__meta">
                                            ';
				echo LR\HtmlHelpers::escapeText($trip->reservations) /* pos 173:45 */;
				echo ' rezervací
                                        </div>
                                    </div>
                                </div>
';

			}

		} else /* pos 178:25 */ {
			echo '                            <p class="admin-toplist__empty">Zatím žádná data.</p>
';
		}
		echo '                    </div>
                </div>
    </div>

    <div class="admin-panel admin-panel--wide">
                <div class="admin-panel__header">
            <span class="admin-panel__title">
                <span class="admin-panel__title-icon">👁</span>
                Nejnavštěvovanější výlet
            </span>
                </div>

                <div class="admin-panel__body">
';
		if ($mostVisitedTrip) /* pos 195:21 */ {
			echo '                        <div class="admin-mostviewed">
                            <div class="admin-mostviewed__name">
                                ';
			echo LR\HtmlHelpers::escapeText($mostVisitedTrip->name) /* pos 198:33 */;
			echo '
                            </div>

                            <div class="admin-mostviewed__highlight">
                                <div class="admin-mostviewed__views">
                            <span class="admin-mostviewed__views-number">
                                ';
			echo LR\HtmlHelpers::escapeText($mostVisitedTrip->views) /* pos 204:33 */;
			echo '
                            </span>
                                    <span class="admin-mostviewed__views-label">
                                zobrazení
                            </span>
                                </div>
                                <div class="admin-mostviewed__extra">
                                    ';
			echo LR\HtmlHelpers::escapeText($mostVisitedTrip->reservations) /* pos 211:37 */;
			echo ' rezervací
                                    (';
			echo LR\HtmlHelpers::escapeText($mostVisitedTrip->conversion) /* pos 212:38 */;
			echo '% konverze)
                                </div>
                            </div>
                        </div>
';
		} else /* pos 216:21 */ {
			echo '                        <p>Zatím žádná zobrazení.</p>
';
		}
		echo '                </div>
    </div>

        <div class="admin-panel admin-panel--wide">
            <div class="admin-panel__header">
            <span class="admin-panel__title">
                <span class="admin-panel__title-icon">⭐</span>
                Hodnocení výletů
            </span>
            </div>

            <div class="admin-panel__body">
';
		if ($ratingsSummary) /* pos 232:17 */ {
			echo '                    <p>Průměrné hodnocení: <strong>';
			echo LR\HtmlHelpers::escapeText(($this->filters->number)($ratingsSummary->avgRating, 1)) /* pos 233:56 */;
			echo '</strong>/5</p>
                    <p>Celkem ';
			echo LR\HtmlHelpers::escapeText($ratingsSummary->count) /* pos 234:31 */;
			echo ' hodnocení.</p>
';
		} else /* pos 235:17 */ {
			echo '                    <p>Zatím žádná hodnocení.</p>
';
		}
		echo '            </div>
        </div>

    </section>
    <section class="admin-dashboard__profit">
        <div class="admin-panel admin-panel--table">
            <div class="admin-panel__header">
            <span class="admin-panel__title">
                <span class="admin-panel__title-icon">💲</span>
                Ziskovost výletů
            </span>
            </div>

            <div class="admin-panel__body">
                <table class="admin-table admin-table--profit">
                    <thead>
                    <tr>
                        <th>Výlet</th>
                        <th class="admin-table__th--right">Rezervace</th>
                        <th class="admin-table__th--right">Tržby</th>
                        <th class="admin-table__th--right">Náklady</th>
                        <th class="admin-table__th--right">Zisk</th>
                    </tr>
                    </thead>
                    <tbody>
';
		foreach ($tripsProfit as $trip) /* pos 263:21 */ {
			echo '                        <tr>
                            <td>';
			echo LR\HtmlHelpers::escapeText($trip->name) /* pos 265:33 */;
			echo '</td>
                            <td class="admin-table__td--right">
                                ';
			echo LR\HtmlHelpers::escapeText($trip->reservations) /* pos 267:33 */;
			echo '
                            </td>
                            <td class="admin-table__td--right">
                                ';
			echo LR\HtmlHelpers::escapeText(($this->filters->number)($trip->revenue, 0)) /* pos 270:33 */;
			echo '&nbsp;$
                            </td>
                            <td class="admin-table__td--right">
                                ';
			echo LR\HtmlHelpers::escapeText(($this->filters->number)($trip->costs, 0)) /* pos 273:33 */;
			echo '&nbsp;$
                            </td>
                            <td class="admin-table__td--right admin-table__profit
           ';
			if ($trip->profit < 0) /* pos 276:12 */ {
				echo ' is-negative ';
			} else /* pos 276:47 */ {
				echo ' is-positive ';
			}
			echo '">
                                ';
			echo LR\HtmlHelpers::escapeText(($this->filters->number)($trip->profit, 0)) /* pos 277:33 */;
			echo '&nbsp;$
                            </td>
                        </tr>
';

		}

		echo '                    </tbody>
                </table>
            </div>
        </div>
    </section>

</div>
';
	}
}
