<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\xampp\htdocs\Matodo\app\Presentation\Admin\UI\Inquiry/default.latte */
final class Template_22f147042a extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent', 'commentSVG' => 'blockCommentSVG', 'garbageSVG' => 'blockGarbageSVG'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('content', get_defined_vars()) /* pos 2:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['inq' => '7'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$css = 'messages' /* pos 1:1 */;
		return get_defined_vars();
	}


	/** {block content} on line 2 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="inquiries-page">
    <h1>Dotazy z formuláře</h1>
    <p class="admin-subtitle">Správa dotazů od zákazníků</p>

';
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($inquiries, $ʟ_it ?? null) as $inq) /* pos 7:5 */ {
			echo '        <div class="inquiry-card">

            <div class="inquiry-card__header">
                <div>
                    <div class="inquiry-card__name">
                        ';
			echo LR\HtmlHelpers::escapeText($inq->name) /* pos 13:25 */;
			echo "\n";
			if ($inq->status == 'responded') /* pos 14:25 */ {
				echo '                            <span class="inquiry-badge inquiry-badge--green">
                                Zodpovězeno
                            </span>
';
			}
			echo '                    </div>

                    <div class="inquiry-card__email">
                        ';
			echo LR\HtmlHelpers::escapeText($inq->email) /* pos 22:25 */;
			echo '
                    </div>
                    <div class="inquiry-card__date">
                        ';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($inq->created_at, 'j. n. Y, H:i')) /* pos 25:25 */;
			echo '
                    </div>
                </div>

                <div class="inquiry-card__actions">
                    <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('respond!', [$inq->id])) /* pos 30:24 */;
			echo '" class="btn btn-outline">
                        ';
			$this->renderBlock('commentSVG', get_defined_vars(), 'html') /* pos 31:25 */;
			echo ' <span>Odpovědět</span>
                    </a>

                    <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('delete!', [$inq->id])) /* pos 34:24 */;
			echo '" class="btn btn-icon btn-danger">
';
			$this->renderBlock('garbageSVG', get_defined_vars(), 'html') /* pos 35:25 */;
			echo '                    </a>
                </div>
            </div>

            <div class="inquiry-card__message">
                ';
			echo LR\HtmlHelpers::escapeText($inq->message) /* pos 41:17 */;
			echo '
            </div>

';
			if ($inq->admin_respond != null) /* pos 44:13 */ {
				echo '                <div class="inquiry-card__answer">
                    <div class="inquiry-card__answer-label">Vaše odpověď:</div>
                    <div class="inquiry-card__answer-text">
                        ';
				echo LR\HtmlHelpers::escapeText($inq->admin_respond) /* pos 48:25 */;
				echo '
                    </div>
                </div>
';
			}
			echo '
        </div>
';

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo '</div>
';
		if (isset($respondInquiry)) /* pos 56:1 */ {
			echo '    <div class="modal-backdrop">
        <div class="modal-window">
            <div class="modal-window__header">
                <h2>Odpovědět na dotaz</h2>
                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('this')) /* pos 61:20 */;
			echo '" class="modal-window__close">×</a>
            </div>

            <div class="modal-window__question">
                <div class="modal-window__question-name">
                    ';
			echo LR\HtmlHelpers::escapeText($respondInquiry->name) /* pos 66:21 */;
			echo '
                </div>
                <div class="modal-window__question-text">
                    ';
			echo LR\HtmlHelpers::escapeText(($this->filters->breaklines)($respondInquiry->message)) /* pos 69:21 */;
			echo '
                </div>
            </div>

            <div class="modal-window__form">
                ';
			$form = $this->global->formsStack[] = $this->global->uiControl['replyForm'] /* pos 74:17 */;
			Nette\Bridges\FormsLatte\Runtime::initializeForm($form);
			echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form, []) /* pos 74:17 */;
			echo '
                    ';
			echo Nette\Bridges\FormsLatte\Runtime::item('id', $this->global)->getControl() /* pos 75:21 */;
			echo '

                    <div class="modal-window__input">
                        ';
			echo ($ʟ_label = Nette\Bridges\FormsLatte\Runtime::item('subject', $this->global)->getLabel()) /* pos 78:25 */;
			echo '
                        ';
			echo Nette\Bridges\FormsLatte\Runtime::item('subject', $this->global)->getControl() /* pos 79:25 */;
			echo '
                            <div class="field-error">
                                ';
			echo LR\HtmlHelpers::escapeText($form['subject']->error) /* pos 81:33 */;
			echo '
                            </div>

                    </div>

                    <div class="modal-window__textarea">
                        ';
			echo ($ʟ_label = Nette\Bridges\FormsLatte\Runtime::item('reply', $this->global)->getLabel()) /* pos 87:25 */;
			echo '
                        ';
			echo Nette\Bridges\FormsLatte\Runtime::item('reply', $this->global)->getControl() /* pos 88:25 */;
			echo '
                            <div class="field-error">
                                ';
			echo LR\HtmlHelpers::escapeText($form['reply']->error) /* pos 90:33 */;
			echo '
                            </div>
                    </div>

                    <button';
			echo ($ʟ_elem = Nette\Bridges\FormsLatte\Runtime::item('send', $this->global)->getControlPart())->addAttributes(['class' => null])->attributes() /* pos 94:29 */;
			echo ' class="modal-submit">
                        ✉ Odeslat odpověď
                    </button>
                ';
			echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack)) /* pos 97:17 */;

			echo '
            </div>
        </div>
    </div>
';
		}
		echo "\n";
	}


	/** {define commentSVG} on line 103 */
	public function blockCommentSVG(array $ʟ_args): void
	{
		echo '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-dots" viewBox="0 0 16 16">
    <path d="M5 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0m4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0m3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2"></path>
    <path d="m2.165 15.803.02-.004c1.83-.363 2.948-.842 3.468-1.105A9 9 0 0 0 8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6a10.4 10.4 0 0 1-.524 2.318l-.003.011a11 11 0 0 1-.244.637c-.079.186.074.394.273.362a22 22 0 0 0 .693-.125m.8-3.108a1 1 0 0 0-.287-.801C1.618 10.83 1 9.468 1 8c0-3.192 3.004-6 7-6s7 2.808 7 6-3.004 6-7 6a8 8 0 0 1-2.088-.272 1 1 0 0 0-.711.074c-.387.196-1.24.57-2.634.893a11 11 0 0 0 .398-2"></path>
</svg>
';
	}


	/** {define garbageSVG} on line 109 */
	public function blockGarbageSVG(array $ʟ_args): void
	{
		echo '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"></path>
    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"></path>
</svg>
';
	}
}
