<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\xampp\htdocs\Matodo\app\Infrastructure\Mail/Templates/ReservationConfirmation.latte */
final class Template_5356ac9cad extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo 'Dobrý den,<br>
<br>
váš rezervační požadavek byl úspěšně přijat. Níže naleznete podrobnosti o vaší rezervaci:<br>
<br>
<strong>Jméno a příjmení:</strong> ';
		echo LR\HtmlHelpers::escapeText($customer_name) /* pos 5:40 */;
		echo '<br>
Datum výletu: ';
		echo LR\HtmlHelpers::escapeText(($this->filters->date)($date, 'j. n. Y')) /* pos 6:16 */;
		echo '<br>
Pro počet osob: ';
		echo LR\HtmlHelpers::escapeText($guests) /* pos 7:18 */;
		echo '<br>
Poznámka: ';
		echo LR\HtmlHelpers::escapeText(($this->filters->breaklines)($note)) /* pos 8:12 */;
		echo '<br>
Výlet: ';
		echo LR\HtmlHelpers::escapeText($trip_name) /* pos 9:9 */;
		echo '<br>
Místo vyzvednutí: ';
		echo LR\HtmlHelpers::escapeText($pickup_point) /* pos 10:21 */;
		echo '<br>
Cena za osobu: ';
		echo LR\HtmlHelpers::escapeText($trip_price) /* pos 11:16 */;
		echo ' USD<br>
<br>
Brzy se Vám ozveme s potvrzením a dalšími informacemi.<br>
S pozdravem,<br>
Tým Matodo
';
	}
}
