<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\xampp\htdocs\Matodo\app\Infrastructure\Mail/Templates/ReservationConfirm.latte */
final class Template_7e63907269 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo 'Dobrý den,<br>
<br>
Vaše rezervace byla úspěšně potvrzena. Níže naleznete podrobnosti o vaší rezervaci:<br>
<br>
<strong>Jméno:</strong> ';
		echo LR\HtmlHelpers::escapeText($name) /* pos 5:26 */;
		echo '<br>
<strong>Datum rezervace:</strong> ';
		echo LR\HtmlHelpers::escapeText(($this->filters->date)($date, 'd.m.Y H:i')) /* pos 6:35 */;
		echo '<br>
Počet osob: ';
		echo LR\HtmlHelpers::escapeText($persons) /* pos 7:14 */;
		echo '<br>
Výlet: ';
		echo LR\HtmlHelpers::escapeText($trip) /* pos 8:9 */;
		echo '<br>
Místo vyzvednutí: ';
		echo LR\HtmlHelpers::escapeText($pickup) /* pos 9:21 */;
		echo '<br>
Čas vyzvednutí: ';
		echo LR\HtmlHelpers::escapeText(($this->filters->date)($time, 'H:i')) /* pos 10:19 */;
		echo '<br>
<hr>
Celková cena: ';
		echo LR\HtmlHelpers::escapeText($total_price) /* pos 12:16 */;
		echo ' USD<br>

Záloha činní: 10% z celkové ceny - ';
		echo LR\HtmlHelpers::escapeText($deposit) /* pos 14:40 */;
		echo ' USD.<br>
Zbývající částka bude splatná na místě.<br>
<br>
Platba zálohy je možná prostřednictvím bankovního převodu na následující účet:<br>
<strong>Číslo účtu:</strong> xxx<br>
<strong>Variabilní symbol:</strong> xxx<br>
<br>
Prosíme, uveďte variabilní symbol při platbě, aby bylo možné vaši platbu správně přiřadit k rezervaci.<br>
<hr>
Děkujeme, že jste si vybrali naši službu. Těšímeme se na Vaši návštěvu!<br>
<br>
S pozdravem,<br>
Tým Matodo';
	}
}
