<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\xampp\htdocs\Matodo\app\Presentation\Admin\UI\Reservations/default.latte */
final class Template_104c5d9389 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('content', get_defined_vars()) /* pos 2:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['res' => '8'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$css = 'reservations' /* pos 1:1 */;
		return get_defined_vars();
	}


	/** {block content} on line 2 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="reservations-page">
    <h1>Rezervace</h1>
    <p class="admin-subtitle">Správa rezervací výletů</p>

    <div class="reservations-list">
';
		foreach ($reservations as $res) /* pos 8:9 */ {
			echo '
            <div class="reservation-card">

                <div class="reservation-card__header">
                    <div>
                        <div class="reservation-card__name">
                            ';
			echo LR\HtmlHelpers::escapeText($res->customer_name) /* pos 15:29 */;
			echo '

                            <span class="reservation-badge reservation-badge-';
			echo LR\HtmlHelpers::escapeAttr($res->status) /* pos 17:78 */;
			echo '">';
			if ($res->status == 'pending') /* pos 17:94 */ {
				echo 'Čeká';
			} elseif ($res->status == 'confirm') /* pos 17:130 */ {
				echo 'Potvrzeno';
			} else /* pos 17:173 */ {
				echo 'Zrušeno';
			}

			echo '</span>
                        </div>

                        <div class="reservation-card__trip">
                            ';
			echo LR\HtmlHelpers::escapeText($res->trip->title) /* pos 21:29 */;
			echo '
                        </div>
                    </div>

                    <div class="reservation-card__actions">
                        <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('detail!', [$res->id])) /* pos 26:28 */;
			echo '" class="btn-rsv btn-rsv--info">ℹ Detail</a>
                        <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('confirm!', [$res->id])) /* pos 27:28 */;
			echo '" class="btn-rsv btn-rsv--ok">✔ Potvrdit</a>
                        <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('email!', [$res->id])) /* pos 28:28 */;
			echo '" class="btn-rsv btn-rsv--email">✉ Email</a>
                        <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('cancel!', [$res->id])) /* pos 29:28 */;
			echo '" class="btn-rsv btn-rsv--danger">🗑 Zrušit</a>
                    </div>
                </div>

                <div class="reservation-card__info">
                    <div class="reservation-info-item">
                        📅 ';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($res->date, 'j. F Y')) /* pos 35:30 */;
			echo '
                    </div>

                    <div class="reservation-info-item">
                        👤 ';
			echo LR\HtmlHelpers::escapeText($res->guests) /* pos 39:30 */;
			echo ' osob
                    </div>

                    <div class="reservation-info-item">
                        ✉ ';
			echo LR\HtmlHelpers::escapeText($res->customer_email) /* pos 43:29 */;
			echo '
                    </div>

                    <div class="reservation-info-item">
                        ☎ ';
			echo LR\HtmlHelpers::escapeText($res->customer_phone) /* pos 47:29 */;
			echo '
                    </div>
                </div>

                <div class="reservation-card__created">
                    Vytvořeno: ';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($res->created_at, 'j. F Y, H:i')) /* pos 52:33 */;
			echo '
                </div>

            </div>

';

		}

		echo '    </div>
</div>
';
		if ($showConfirmModal && $confirmReservation) /* pos 60:1 */ {
			echo '    <div class="reservations-modal-backdrop">
        <div class="reservations-modal reservations-modal--confirm">
            <div class="reservations-modal__header">
                <h2>Potvrdit rezervaci</h2>
                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('this')) /* pos 65:20 */;
			echo '" class="reservations-modal__close">×</a>
            </div>

            <div class="reservations-modal__info">
                <div><strong>';
			echo LR\HtmlHelpers::escapeText($confirmReservation->customer_name) /* pos 69:30 */;
			echo '</strong></div>
                <div>Výlet: <strong>';
			echo LR\HtmlHelpers::escapeText($confirmReservation->trip->title) /* pos 70:38 */;
			echo '</strong></div>
                <div>Datum: <strong>';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($confirmReservation->date, 'j. n. Y')) /* pos 71:37 */;
			echo '</strong></div>
                <div>Osob: <strong>';
			echo LR\HtmlHelpers::escapeText($confirmReservation->guests) /* pos 72:36 */;
			echo '</strong></div>
            </div>

            <div class="reservations-modal__body">
                ';
			$form = $this->global->formsStack[] = $this->global->uiControl['reservationConfirmForm'] /* pos 76:17 */;
			Nette\Bridges\FormsLatte\Runtime::initializeForm($form);
			echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form, []) /* pos 76:17 */;
			echo '
                    ';
			echo Nette\Bridges\FormsLatte\Runtime::item('id', $this->global)->getControl() /* pos 77:21 */;
			echo '

                    <div class="reservations-form__group">
                        <label for="frm-reservationConfirmForm-time">Čas vyzvednutí *</label>
                        ';
			echo Nette\Bridges\FormsLatte\Runtime::item('time', $this->global)->getControl() /* pos 81:25 */;
			echo '
                    </div>

                    <button';
			echo ($ʟ_elem = Nette\Bridges\FormsLatte\Runtime::item('send', $this->global)->getControlPart())->addAttributes(['class' => null])->attributes() /* pos 84:29 */;
			echo ' class="reservations-modal__submit">
                        Potvrdit rezervaci
                    </button>
                ';
			echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack)) /* pos 87:17 */;

			echo '
            </div>
        </div>
    </div>
';
		}
		echo "\n";
		if ($showEmailModal && $emailReservation) /* pos 94:1 */ {
			echo '    <div class="reservations-modal-backdrop">
        <div class="reservations-modal reservations-modal--email">
            <div class="reservations-modal__header">
                <h2>E-mail k rezervaci</h2>
                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('this')) /* pos 99:20 */;
			echo '" class="reservations-modal__close">×</a>
            </div>

            <div class="reservations-modal__info">
                <div><strong>';
			echo LR\HtmlHelpers::escapeText($emailReservation->customer_name) /* pos 103:30 */;
			echo '</strong></div>
                <div>Výlet: <strong>';
			echo LR\HtmlHelpers::escapeText($emailReservation->trip->title) /* pos 104:38 */;
			echo '</strong></div>
                <div>Email: <strong>';
			echo LR\HtmlHelpers::escapeText($emailReservation->customer_email) /* pos 105:37 */;
			echo '</strong></div>
            </div>

            <div class="reservations-modal__body">
                ';
			$form = $this->global->formsStack[] = $this->global->uiControl['emailForm'] /* pos 109:17 */;
			Nette\Bridges\FormsLatte\Runtime::initializeForm($form);
			echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form, []) /* pos 109:17 */;
			echo '
                    ';
			echo Nette\Bridges\FormsLatte\Runtime::item('id', $this->global)->getControl() /* pos 110:21 */;
			echo '

                    <div class="reservations-form__group">
                        <label for="frm-emailForm-subject">Předmět *</label>
                        ';
			echo Nette\Bridges\FormsLatte\Runtime::item('subject', $this->global)->getControl() /* pos 114:25 */;
			echo '
                    </div>

                    <div class="reservations-form__group">
                        <label for="frm-emailForm-message">Zpráva *</label>
                        ';
			echo Nette\Bridges\FormsLatte\Runtime::item('message', $this->global)->getControl() /* pos 119:25 */;
			echo '
                    </div>

                    <button';
			echo ($ʟ_elem = Nette\Bridges\FormsLatte\Runtime::item('send', $this->global)->getControlPart())->addAttributes(['class' => null])->attributes() /* pos 122:29 */;
			echo ' class="reservations-modal__submit">
                        Odeslat e-mail
                    </button>
                ';
			echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack)) /* pos 125:17 */;

			echo '
            </div>
        </div>
    </div>
';
		}
		if ($showDetailModal && $detailReservation) /* pos 131:1 */ {
			echo '    <div class="reservations-modal-backdrop">
        <div class="reservations-modal reservations-modal--detail">
            <div class="reservations-modal__header">
                <h2>Detail rezervace</h2>
                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('this')) /* pos 136:20 */;
			echo '" class="reservations-modal__close">×</a>
            </div>

            <div class="reservation-detail">

                <section class="reservation-detail__section">
                    <h3>Zákazník</h3>

                    <div class="reservation-detail__row">
                        <div class="reservation-detail__field">
                            <div class="reservation-detail__label">Jméno:</div>
                            <div class="reservation-detail__value">
                                ';
			echo LR\HtmlHelpers::escapeText($detailReservation->customer_name) /* pos 148:33 */;
			echo '
                            </div>
                        </div>

                        <div class="reservation-detail__field">
                            <div class="reservation-detail__label">Email:</div>
                            <div class="reservation-detail__value">
                                ';
			echo LR\HtmlHelpers::escapeText($detailReservation->customer_email) /* pos 155:33 */;
			echo '
                            </div>
                        </div>
                    </div>

                    <div class="reservation-detail__row">
                        <div class="reservation-detail__field">
                            <div class="reservation-detail__label">Telefon:</div>
                            <div class="reservation-detail__value">
                                ';
			echo LR\HtmlHelpers::escapeText($detailReservation->customer_phone) /* pos 164:33 */;
			echo '
                            </div>
                        </div>

                        <div class="reservation-detail__field">
                            <div class="reservation-detail__label">Počet osob:</div>
                            <div class="reservation-detail__value">
                                ';
			echo LR\HtmlHelpers::escapeText($detailReservation->guests) /* pos 171:33 */;
			echo '
                            </div>
                        </div>
                    </div>

                    <div class="reservation-detail__row">
                        <div class="reservation-detail__field">
                            <div class="reservation-detail__label">Místo vyzvednutí:</div>
                            <div class="reservation-detail__value">
                                ';
			echo LR\HtmlHelpers::escapeText($detailReservation->pickup_point) /* pos 180:33 */;
			echo '
                            </div>
                        </div>

                        <div class="reservation-detail__field">
                            <div class="reservation-detail__label">Poznámka:</div>
                            <div class="reservation-detail__value">
                                ';
			echo LR\HtmlHelpers::escapeText($detailReservation->notes) /* pos 187:33 */;
			echo '
                            </div>
                        </div>
                    </div>
                </section>

                <section class="reservation-detail__section">
                    <h3>Výlet</h3>

                    <div class="reservation-detail__row">
                        <div class="reservation-detail__field reservation-detail__field--full">
                            <div class="reservation-detail__label">Název:</div>
                            <div class="reservation-detail__value">
                                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Front:Excursion:default', [$detailReservation->trip->id])) /* pos 200:36 */;
			echo '"
                                        target="_blank"
                                        class="reservation-detail__trip-link">
                                    ';
			echo LR\HtmlHelpers::escapeText($detailReservation->trip->title) /* pos 203:37 */;
			echo '
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="reservation-detail__row">
                        <div class="reservation-detail__field">
                            <div class="reservation-detail__label">Lokace:</div>
                            <div class="reservation-detail__value">
                                ';
			echo LR\HtmlHelpers::escapeText($detailReservation->trip->location) /* pos 213:33 */;
			echo '
                            </div>
                        </div>

                        <div class="reservation-detail__field">
                            <div class="reservation-detail__label">Délka:</div>
                            <div class="reservation-detail__value">
                                ';
			echo LR\HtmlHelpers::escapeText($detailReservation->trip->duration) /* pos 220:33 */;
			echo '
                            </div>
                        </div>
                    </div>

                    <div class="reservation-detail__row">
                        <div class="reservation-detail__field">
                            <div class="reservation-detail__label">Cena:</div>
                            <div class="reservation-detail__value">
                                ';
			echo LR\HtmlHelpers::escapeText(($this->filters->number)($detailReservation->trip->price, 0, ',', ' ')) /* pos 229:33 */;
			echo ' USD
                            </div>
                        </div>
                    </div>
                </section>

                <section class="reservation-detail__section">
                    <h3>Rezervace</h3>

                    <div class="reservation-detail__row">
                        <div class="reservation-detail__field">
                            <div class="reservation-detail__label">Datum:</div>
                            <div class="reservation-detail__value">
                                ';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($detailReservation->date, 'j. n. Y')) /* pos 242:33 */;
			echo '
                            </div>
                        </div>

                        <div class="reservation-detail__field">
                            <div class="reservation-detail__label">Status:</div>
                            <div class="reservation-detail__value">
                                <span class="reservation-status reservation-status--';
			echo LR\HtmlHelpers::escapeAttr($detailReservation->status) /* pos 249:85 */;
			echo '">
';
			if ($detailReservation->status === 'confirm') /* pos 250:37 */ {
				echo '                                        Potvrzeno
';
			} elseif ($detailReservation->status === 'canceled') /* pos 252:37 */ {
				echo '                                        Zrušeno
';
			} else /* pos 254:37 */ {
				echo '                                        Čeká
';
			}

			echo '                                </span>
                            </div>
                        </div>
                    </div>

                    <div class="reservation-detail__row">
                        <div class="reservation-detail__field reservation-detail__field--full">
                            <div class="reservation-detail__label">Vytvořeno:</div>
                            <div class="reservation-detail__value">
                                ';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($detailReservation->created_at, 'j. n. Y, H:i')) /* pos 266:33 */;
			echo '
                            </div>
                        </div>
                    </div>
                </section>

            </div>
        </div>
    </div>
';
		}
		echo "\n";
	}
}
