<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\xampp\htdocs\Matodo\app\Presentation\Admin\UI\Transfer/default.latte */
final class Template_de199cbef3 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['t' => '40'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$css = 'transfer' /* pos 1:1 */;
		$js = 'transfer' /* pos 2:1 */;
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<section class="transfer-admin">

    <header class="transfer-admin__header">
        <h1 class="transfer-admin__title">Správa Transferů</h1>
        <p class="transfer-admin__subtitle">Rezervace luxusního Chevrolet Suburban</p>
    </header>

  <div class="transfer-stats">
            <div class="transfer-stat">
                <div class="transfer-stat__label">Celkem rezervací</div>
                <div class="transfer-stat__value">';
		echo LR\HtmlHelpers::escapeText($stats['total']) /* pos 15:51 */;
		echo '</div>
            </div>

            <div class="transfer-stat">
                <div class="transfer-stat__label">Čeká na potvrzení</div>
                <div class="transfer-stat__value transfer-stat__value--waiting">';
		echo LR\HtmlHelpers::escapeText($stats['waiting']) /* pos 20:81 */;
		echo '</div>
            </div>

            <div class="transfer-stat">
                <div class="transfer-stat__label">Potvrzeno</div>
                <div class="transfer-stat__value transfer-stat__value--confirmed">';
		echo LR\HtmlHelpers::escapeText($stats['confirmed']) /* pos 25:83 */;
		echo '</div>
            </div>
  </div>

    <div class="transfer-panel">
        <div class="transfer-panel__head">
            <div class="transfer-panel__title">
                <span class="transfer-panel__icon" aria-hidden="true">🚗</span>
                Rezervace transferů
            </div>
        </div>

        <div class="transfer-panel__body">

';
		foreach ($transfers as $t) /* pos 40:13 */ {
			echo '                <article class="transfer-item">
                    <div class="transfer-item__main">

                        <div class="transfer-item__top">
                            <div class="transfer-item__name">';
			echo LR\HtmlHelpers::escapeText($t->customer_name) /* pos 45:62 */;
			echo '</div>

';
			if ($t->status === 'pending') /* pos 47:29 */ {
				echo '                                <span class="transfer-badge transfer-badge--waiting">Čeká</span>
';
			} elseif ($t->status === 'confirm') /* pos 49:29 */ {
				echo '                                <span class="transfer-badge transfer-badge--confirmed">Potvrzeno</span>
';
			} else /* pos 51:29 */ {
				echo '                                <span class="transfer-badge">Zrušeno</span>
';
			}

			echo '                        </div>

                        <div class="transfer-item__meta">
                            <div class="transfer-meta">
                                <span class="transfer-meta__icon" aria-hidden="true">📅</span>
                                <span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($t->pickup_date, 'j. n. Y')) /* pos 59:39 */;
			echo '</span>
                            </div>

                            <div class="transfer-meta">
                                <span class="transfer-meta__icon" aria-hidden="true">🕒</span>
                                <span>';
			echo LR\HtmlHelpers::escapeText($t->pickup_time->format('%H:%I')) /* pos 64:39 */;
			echo '</span>
                            </div>

                            <div class="transfer-meta">
                                <span class="transfer-meta__icon" aria-hidden="true">👥</span>
                                <span>';
			echo LR\HtmlHelpers::escapeText($t->passagers) /* pos 69:39 */;
			echo '</span>
                            </div>
                        </div>

                        <div class="transfer-item__route">
                            <span class="transfer-meta__icon" aria-hidden="true">📍</span>
                            <span>';
			echo LR\HtmlHelpers::escapeText($t->pickup_location) /* pos 75:35 */;
			echo ' → ';
			echo LR\HtmlHelpers::escapeText($t->dropoff_location) /* pos 75:61 */;
			echo '</span>
                        </div>

                    </div>

                    <div class="transfer-item__actions">
                        <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('detail!', ['id' => $t->id])) /* pos 81:28 */;
			echo '" class="tbtn tbtn--ghost">ℹ Detail</a>
                        <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('confirm!', ['id' => $t->id])) /* pos 82:28 */;
			echo '" class="tbtn tbtn--primary">Potvrdit</a>
                        <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('email!', ['id' => $t->id])) /* pos 83:28 */;
			echo '" class="tbtn tbtn--ghost">Email</a>
                        <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('delete!', ['id' => $t->id])) /* pos 84:28 */;
			echo '"
                                class="tbtn tbtn--danger"
                                onclick="return confirm(\'Opravdu smazat rezervaci?\')">Smazat</a>
                    </div>

                </article>
';

		}

		echo '
        </div>
    </div>

</section>

';
		if ($showTransferDetailModal) /* pos 97:1 */ {
			echo '    <div class="tdm-backdrop" data-modal="transfer-detail">
        <div class="tdm-modal" role="dialog" aria-modal="true" aria-label="Detail rezervace transferu">

            <div class="tdm-header">
                <h2 class="tdm-title">Detail rezervace transferu</h2>
                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('this')) /* pos 103:20 */;
			echo '" class="tdm-close" aria-label="Zavřít" data-modal-close>
                    ×
                </a>
            </div>

            <div class="tdm-body">

                <div class="tdm-topgrid">
                    <div class="tdm-block">
                        <div class="tdm-label">Zákazník</div>
                        <div class="tdm-strong">';
			echo LR\HtmlHelpers::escapeText($detail->customer_name) /* pos 113:49 */;
			echo '</div>
                    </div>

                    <div class="tdm-block tdm-block--right">
                        <div class="tdm-label">Stav</div>

';
			if ($detail->status === 'pending') /* pos 119:25 */ {
				echo '                            <span class="tdm-badge tdm-badge--waiting">Čeká</span>
';
			} elseif ($detail->status === 'confirm') /* pos 121:25 */ {
				echo '                            <span class="tdm-badge tdm-badge--confirmed">Potvrzeno</span>
';
			} else /* pos 123:25 */ {
				echo '                            <span class="tdm-badge">Zrušeno</span>
';
			}

			echo '                    </div>

                    <div class="tdm-contact tdm-contact--email">
                        <span class="tdm-ico" aria-hidden="true">✉️</span>
                        <a href="mailto:';
			echo LR\HtmlHelpers::escapeAttr($detail->customer_email) /* pos 130:41 */;
			echo '" class="tdm-link">';
			echo LR\HtmlHelpers::escapeText($detail->customer_email) /* pos 130:85 */;
			echo '</a>
                    </div>

                    <div class="tdm-contact tdm-contact--phone">
                        <span class="tdm-ico" aria-hidden="true">📞</span>
                        <a href="tel:';
			echo LR\HtmlHelpers::escapeAttr($detail->customer_phone) /* pos 135:38 */;
			echo '" class="tdm-link">';
			echo LR\HtmlHelpers::escapeText($detail->customer_phone) /* pos 135:82 */;
			echo '</a>
                    </div>
                </div>

                <hr class="tdm-sep">

                <div class="tdm-meta">
                    <div class="tdm-meta-item">
                        <span class="tdm-ico" aria-hidden="true">📅</span>
                        <span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($detail->pickup_date, 'j. n. Y')) /* pos 144:31 */;
			echo '</span>
                    </div>

                    <div class="tdm-meta-item">
                        <span class="tdm-ico" aria-hidden="true">🕒</span>
                        <span>';
			echo LR\HtmlHelpers::escapeText($detail->pickup_time->format('%H:%I')) /* pos 149:31 */;
			echo '</span>
                    </div>

                    <div class="tdm-meta-item">
                        <span class="tdm-ico" aria-hidden="true">👥</span>
                        <span>';
			echo LR\HtmlHelpers::escapeText($detail->passagers) /* pos 154:31 */;
			echo ' pasažérů</span>
                    </div>
                </div>

                <hr class="tdm-sep">

                <div class="tdm-section">
                    <div class="tdm-label">Trasa</div>

                    <div class="tdm-route">
                        <div class="tdm-route-row">
                            <div class="tdm-route-k">Z:</div>
                            <div class="tdm-route-v">';
			echo LR\HtmlHelpers::escapeText($detail->pickup_location) /* pos 166:54 */;
			echo '</div>
                        </div>
                        <div class="tdm-route-row">
                            <div class="tdm-route-k">Do:</div>
                            <div class="tdm-route-v">';
			echo LR\HtmlHelpers::escapeText($detail->dropoff_location) /* pos 170:54 */;
			echo '</div>
                        </div>
                    </div>
                </div>

                <div class="tdm-footer">
                    Vytvořeno: ';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($detail->created_at, 'j. n. Y H:i')) /* pos 176:33 */;
			echo '
                </div>

            </div>
        </div>
    </div>
';
		}
		echo "\n";
		if ($showEmailModal && $emailTransfer) /* pos 184:1 */ {
			echo '    <div class="reservations-modal-backdrop">
        <div class="reservations-modal reservations-modal--email">
            <div class="reservations-modal__header">
                <h2>E-mail k rezervaci</h2>
                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('this')) /* pos 189:20 */;
			echo '" class="reservations-modal__close">×</a>
            </div>

            <div class="reservations-modal__info">
                <div><strong>';
			echo LR\HtmlHelpers::escapeText($emailTransfer->customer_name) /* pos 193:30 */;
			echo '</strong></div>
                <div>Email: <strong>';
			echo LR\HtmlHelpers::escapeText($emailTransfer->customer_email) /* pos 194:37 */;
			echo '</strong></div>
            </div>

            <div class="reservations-modal__body">
                ';
			$form = $this->global->formsStack[] = $this->global->uiControl['emailForm'] /* pos 198:17 */;
			Nette\Bridges\FormsLatte\Runtime::initializeForm($form);
			echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form, []) /* pos 198:17 */;
			echo '
                    ';
			echo Nette\Bridges\FormsLatte\Runtime::item('id', $this->global)->getControl() /* pos 199:21 */;
			echo '

                    <div class="reservations-form__group">
                        <label for="frm-emailForm-subject">Předmět *</label>
                        ';
			echo Nette\Bridges\FormsLatte\Runtime::item('subject', $this->global)->getControl() /* pos 203:25 */;
			echo '
                    </div>

                    <div class="reservations-form__group">
                        <label for="frm-emailForm-message">Zpráva *</label>
                        ';
			echo Nette\Bridges\FormsLatte\Runtime::item('message', $this->global)->getControl() /* pos 208:25 */;
			echo '
                    </div>

                    <button';
			echo ($ʟ_elem = Nette\Bridges\FormsLatte\Runtime::item('send', $this->global)->getControlPart())->addAttributes(['class' => null])->attributes() /* pos 211:29 */;
			echo ' class="reservations-modal__submit">
                        Odeslat e-mail
                    </button>
                ';
			echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack)) /* pos 214:17 */;

			echo '
            </div>
        </div>
    </div>
';
		}
		if ($showConfirmModal && $confirmTransfer) /* pos 219:1 */ {
			echo '    <div class="reservations-modal-backdrop">
        <div class="reservations-modal reservations-modal--confirm">
            <div class="reservations-modal__header">
                <h2>Potvrdit rezervaci</h2>
                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('this')) /* pos 224:20 */;
			echo '" class="reservations-modal__close">×</a>
            </div>

            <div class="reservations-modal__info">
                <div><strong>';
			echo LR\HtmlHelpers::escapeText($confirmTransfer->customer_name) /* pos 228:30 */;
			echo '</strong></div>
                <div>Datum: <strong>';
			echo LR\HtmlHelpers::escapeText(($this->filters->date)($confirmTransfer->pickup_date, 'j. n. Y')) /* pos 229:37 */;
			echo ' ';
			echo LR\HtmlHelpers::escapeText($confirmTransfer->pickup_time->format('%H:%I')) /* pos 229:84 */;
			echo '</strong></div>
                <div>Osob: <strong>';
			echo LR\HtmlHelpers::escapeText($confirmTransfer->passagers) /* pos 230:36 */;
			echo '</strong></div>
            </div>

            <div class="reservations-modal__body">
                ';
			$form = $this->global->formsStack[] = $this->global->uiControl['transferConfirmForm'] /* pos 234:17 */;
			Nette\Bridges\FormsLatte\Runtime::initializeForm($form);
			echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form, []) /* pos 234:17 */;
			echo '
                    ';
			echo Nette\Bridges\FormsLatte\Runtime::item('id', $this->global)->getControl() /* pos 235:21 */;
			echo '

                    <div class="reservations-form__group">
                        <label for="frm-reservationConfirmForm-time">Částka za transfer v USD *</label>
                        ';
			echo Nette\Bridges\FormsLatte\Runtime::item('price', $this->global)->getControl() /* pos 239:25 */;
			echo '
                    </div>

                    <button';
			echo ($ʟ_elem = Nette\Bridges\FormsLatte\Runtime::item('send', $this->global)->getControlPart())->addAttributes(['class' => null])->attributes() /* pos 242:29 */;
			echo ' class="reservations-modal__submit">
                        Potvrdit rezervaci
                    </button>
                ';
			echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack)) /* pos 245:17 */;

			echo '
            </div>
        </div>
    </div>
';
		}
		echo "\n";
	}
}
