<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\xampp\htdocs\Matodo\app\Presentation\Admin\UI\Trips/default.latte */
final class Template_a24b2ad5fc extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent', 'garbageSVG' => 'blockGarbageSVG', 'editSVG' => 'blockEditSVG', 'addSVG' => 'blockAddSVG'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('content', get_defined_vars()) /* pos 2:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['trip' => '18'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$css = 'trips' /* pos 1:1 */;
		return get_defined_vars();
	}


	/** {block content} on line 2 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="trips-page">

    <div class="trips-header">
        <div>
            <h1>Správa výletů</h1>
            <p>Přidávání, úprava a mazání výletů</p>
        </div>

        <a href="';
		echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('new!')) /* pos 11:12 */;
		echo '" class="trips-new-btn">
            <span>＋</span>
            <span>Nový výlet</span>
        </a>
    </div>

    <div class="trips-grid">
';
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($trips, $ʟ_it ?? null) as $trip) /* pos 18:9 */ {
			echo '            <div class="trip-card">
                <div class="trip-card__image-wrapper">
                    <img src="';
			echo LR\HtmlHelpers::escapeAttr($basePath) /* pos 21:31 */;
			echo '/img/';
			echo LR\HtmlHelpers::escapeAttr($trip->img_folder) /* pos 21:47 */;
			echo '/';
			echo LR\HtmlHelpers::escapeAttr($trip->img_name) /* pos 21:67 */;
			echo '" alt="{';
			echo LR\HtmlHelpers::escapeAttr($trip->img_name) /* pos 21:92 */;
			echo '" class="trip-card__image">

                    <div class="trip-card__badge">
                        ';
			echo LR\HtmlHelpers::escapeText($trip->price) /* pos 24:25 */;
			echo ' $
                    </div>
                </div>

                <div class="trip-card__body">
                    <h2 class="trip-card__title">';
			echo LR\HtmlHelpers::escapeText($trip->title) /* pos 29:50 */;
			echo '</h2>

                    <p class="trip-card__description">
                        ';
			echo LR\HtmlHelpers::escapeText($trip->description) /* pos 32:25 */;
			echo '
                    </p>

                    <div class="trip-card__meta">
                        <span>⏱ ';
			echo LR\HtmlHelpers::escapeText($trip->duration) /* pos 36:35 */;
			echo '</span>
                        <span>📍 ';
			echo LR\HtmlHelpers::escapeText($trip->location) /* pos 37:36 */;
			echo '</span>
                        <span>👥 ';
			echo LR\HtmlHelpers::escapeText($trip->group_size) /* pos 38:36 */;
			echo '</span>
                    </div>

                    <div class="trip-card__actions">
                        <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('addSchedule!', [$trip->id])) /* pos 42:28 */;
			echo '" class="btn-trip btn-trip--primary">
                            ';
			$this->renderBlock('addSVG', get_defined_vars(), 'html') /* pos 43:29 */;
			echo ' Přidat termíny
                        </a>
                        <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('edit!', [$trip->id])) /* pos 45:28 */;
			echo '" class="btn-trip btn-trip--primary">
                            ';
			$this->renderBlock('editSVG', get_defined_vars(), 'html') /* pos 46:29 */;
			echo ' Upravit
                        </a>

                        <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('delete!', [$trip->id])) /* pos 49:28 */;
			echo '" class="btn-trip btn-trip--danger">
';
			$this->renderBlock('garbageSVG', get_defined_vars(), 'html') /* pos 50:29 */;
			echo '                        </a>
                    </div>
                </div>
            </div>
';

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo '    </div>

</div>
';
		if ($showTripModal) /* pos 59:1 */ {
			echo '    <div class="modal-backdrop">
        <div class="modal-window modal-window--trip">
            <div class="modal-window__header">
                <h2>Nový výlet</h2>
                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('this')) /* pos 64:20 */;
			echo '" class="modal-window__close">×</a>
            </div>

            ';
			$form = $this->global->formsStack[] = $this->global->uiControl['tripForm'] /* pos 67:13 */;
			Nette\Bridges\FormsLatte\Runtime::initializeForm($form);
			echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form, []) /* pos 67:13 */;
			echo '
                <div class="trip-form">

                    <div class="trip-form__row">
                        <div class="trip-form__group">
                            <label>Cena Bayahibe</label>
                            ';
			echo Nette\Bridges\FormsLatte\Runtime::item('price', $this->global)->getControl() /* pos 73:29 */;
			echo '
                        </div>
                        <div class="trip-form__group">
                            <label>Náklady</label>
                            ';
			echo Nette\Bridges\FormsLatte\Runtime::item('cost', $this->global)->getControl() /* pos 77:29 */;
			echo '
                        </div>
                    </div>
                    <div class="trip-form__row">
                        <div class="trip-form__group">
                            <label>Cena Punta Cana</label>
                            ';
			echo Nette\Bridges\FormsLatte\Runtime::item('price_pc', $this->global)->getControl() /* pos 83:29 */;
			echo '
                        </div>
                        <div class="trip-form__group">
                            <label>Cena Juan Dolio</label>
                            ';
			echo Nette\Bridges\FormsLatte\Runtime::item('price_jd', $this->global)->getControl() /* pos 87:29 */;
			echo '
                        </div>
                    </div>

                    <div class="trip-form__group">
                        <label>Název</label>
                        ';
			echo Nette\Bridges\FormsLatte\Runtime::item('title', $this->global)->getControl() /* pos 93:25 */;
			echo '
                    </div>

                    <div class="trip-form__group">
                        <label>Krátký popis</label>
                        ';
			echo Nette\Bridges\FormsLatte\Runtime::item('description', $this->global)->getControl() /* pos 98:25 */;
			echo '
                    </div>

                    <div class="trip-form__group">
                        <label>Plný popis</label>
                        ';
			echo Nette\Bridges\FormsLatte\Runtime::item('full_description', $this->global)->getControl() /* pos 103:25 */;
			echo '
                    </div>

                    <div class="trip-form__row">
                        <div class="trip-form__group">
                            <label>Délka trvání</label>
                            ';
			echo Nette\Bridges\FormsLatte\Runtime::item('duration', $this->global)->getControl() /* pos 109:29 */;
			echo '
                        </div>
                        <div class="trip-form__group">
                            <label>Velikost skupiny</label>
                            ';
			echo Nette\Bridges\FormsLatte\Runtime::item('groupSize', $this->global)->getControl() /* pos 113:29 */;
			echo '
                        </div>
                        <div class="trip-form__group">
                            <label>Lokalita</label>
                            ';
			echo Nette\Bridges\FormsLatte\Runtime::item('location', $this->global)->getControl() /* pos 117:29 */;
			echo '
                        </div>
                    </div>

                    <div class="trip-form__group">
                        <label>Obrázek</label>
                        ';
			echo Nette\Bridges\FormsLatte\Runtime::item('image', $this->global)->getControl() /* pos 123:25 */;
			echo '
                    </div>

                    <div class="trip-form__row trip-form__row--textarea">
                        <div class="trip-form__group">
                            <label>Zahrnuto (každý řádek = položka)</label>
                            ';
			echo Nette\Bridges\FormsLatte\Runtime::item('included', $this->global)->getControl() /* pos 129:29 */;
			echo '
                        </div>
                        <div class="trip-form__group">
                            <label>Nezahrnuto (každý řádek = položka)</label>
                            ';
			echo Nette\Bridges\FormsLatte\Runtime::item('not_included', $this->global)->getControl() /* pos 133:29 */;
			echo '
                        </div>
                    </div>

                    <button';
			echo ($ʟ_elem = Nette\Bridges\FormsLatte\Runtime::item('save', $this->global)->getControlPart())->addAttributes(['class' => null])->attributes() /* pos 137:29 */;
			echo ' class="trip-modal-submit">
                        Vytvořit výlet
                    </button>
                </div>
            ';
			echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack)) /* pos 141:13 */;

			echo '
        </div>
    </div>
';
		}
		echo "\n";
		if ($showScheduleModal) /* pos 146:1 */ {
			echo '    <div class="modal-backdrop">
        <div class="modal-window modal-window--trip">
            <div class="modal-window__header">
                <h2>Nový termín</h2>
                <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('this')) /* pos 151:20 */;
			echo '" class="modal-window__close">×</a>
            </div>

            ';
			$form = $this->global->formsStack[] = $this->global->uiControl['scheduleForm'] /* pos 154:13 */;
			Nette\Bridges\FormsLatte\Runtime::initializeForm($form);
			echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form, []) /* pos 154:13 */;
			echo '
                <div class="trip-form">
                    <div class="trip-form__row">
                        <div class="trip-form__group">
                            <label>Datum výletu</label>
                            ';
			echo Nette\Bridges\FormsLatte\Runtime::item('date', $this->global)->getControl() /* pos 159:29 */;
			echo '
                        </div>
                        <div class="trip-form__group">
                            <label>Max lidí</label>
                            ';
			echo Nette\Bridges\FormsLatte\Runtime::item('max_guest', $this->global)->getControl() /* pos 163:29 */;
			echo '
                        </div>
                    </div>
                    <div class="trip-form__group">
                        <label>Poznámky</label>
                        ';
			echo Nette\Bridges\FormsLatte\Runtime::item('notes', $this->global)->getControl() /* pos 168:25 */;
			echo '
                    </div>
                    <button';
			echo ($ʟ_elem = Nette\Bridges\FormsLatte\Runtime::item('send', $this->global)->getControlPart())->addAttributes(['class' => null])->attributes() /* pos 170:29 */;
			echo ' class="trip-modal-submit">
                        Vytvořit termín
                    </button>
                </div>
            ';
			echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack)) /* pos 174:13 */;

			echo '
        </div>
    </div>
';
		}
		echo '


';
	}


	/** {define garbageSVG} on line 179 */
	public function blockGarbageSVG(array $ʟ_args): void
	{
		echo '    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"></path>
        <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"></path>
    </svg>
';
	}


	/** {define editSVG} on line 185 */
	public function blockEditSVG(array $ʟ_args): void
	{
		echo '    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5z"></path>
    </svg>
';
	}


	/** {define addSVG} on line 190 */
	public function blockAddSVG(array $ʟ_args): void
	{
		echo '    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3z"></path>
    </svg>
';
	}
}
